---
- name: set NTP servers
  hosts: networksw

  tasks:
    - name: set NTP servers
      cisco.ios.ios_ntp:
        server: "{{ntp}}"
        logging: false
        state: present

    - name: Save Config
      cisco.ios.ios_config:
        save_when: modified    
   