---
- name: set NTP servers
  hosts: itbuilding

  tasks:
    - name: set NTP servers
      cisco.ios.ios_ntp:
        server: "{{ item }}"
        logging: false
        state: present
      loop: "{{ ntp.split('\n') }}"

    - name: Save Config
      cisco.ios.ios_config:
        save_when: modified    
   